language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile-rails.3.2.x
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Hx6h2wxwRQWNkFhjMSslbqHP4JYVh4pMhLj5xAIhdzGApWifrkb6M6rYkaK4DBpDGQFh/EfOaxWr2v6fJKCDuBpr1t6amIN3/rjQLQKPyD0afM3Vkhw0bTTmpOS6SmmYMBCizv1iDYvzT4WI7W9U6Cm3y6QsjQXWmIrskSPsiGU=
